In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/Volumes/study/A_data-science/Python-Code/Feature Engineering /PipeLine/.train.csv')

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
# drop couple columns 
df.drop(columns = ['PassengerId', 'Name', 'Ticket', 'Cabin'],inplace = True)

In [12]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
# Missing values in data sets
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [25]:
# Step -> train_test_split
from sklearn.model_selection import train_test_split

X = df.drop(columns=['Survived'])

Y = df['Survived']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state = 40)

In [22]:
X_train.head()

     Pclass     Sex   Age  SibSp  Parch      Fare Embarked
661       3    male  40.0      0      0    7.2250        C
393       1  female  23.0      1      0  113.2750        C
266       3    male  16.0      4      1   39.6875        S
144       2    male  18.0      0      0   11.5000        S
446       2  female  13.0      0      1   19.5000        S

In [23]:
Y_train.head()

661    0
393    1
266    0
144    0
446    1
Name: Survived, dtype: int64

In [26]:
X_train.head(1)

     Pclass   Sex   Age  SibSp  Parch   Fare Embarked
661       3  male  40.0      0      0  7.225        C

In [41]:
# SimpleImputer 
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
trf1 = ColumnTransformer([
        ('impute_age', SimpleImputer(),['Age']), # ('impute_age', SimpleImputer(),[02] | columns of index)
        ('impute_Embarked', SimpleImputer(strategy = 'most_frequent'), [6])




], remainder = 'passthrough')

In [43]:
# OneHot encoder 

from sklearn.preprocessing import OneHotEncoder
trf2 = ColumnTransformer([
    ('Ohe_sex_embarked', OneHotEncoder(sparse_output = False , handle_unknown = 'ignore'), [1,6])

], remainder = 'passthrouh')

In [ ]:
from sklearn.preprocessing import