### NPL
Natural Language Processing (NLP) is a subfield of AI focused on making machines to understand, interpret, generate and respond to human language. Deep Learning (DL) involves training neural networks to extract hierarchical features from data. NLP using Deep Learning integrates DL models to better capture the meaning and language, improving performance in complex tasks. This has significantly advanced areas like machine translation, sentiment analysis, chatbots, and summarization.

Data Set link : https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [ ]:
import os 
import pandas as pd
# get current working directory
os.getcwd()

'/Volumes/study/A_data-science/Python-Code/NPL'

In [ ]:
# for google drive 
''' 
from google.colab import drive
drive.mount('/content/drive')
'''

In [2]:
df = pd.read_csv('/Volumes/study/A_data-science/Python-Code/NPL/IMDB Dataset.csv')

In [3]:
df.shape

(50000, 2)

In [ ]:
# take 10000 from 50000

df = df.head(10000)

In [5]:
df.shape

(10000, 2)

In [6]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

### Lower case converting

In [9]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [10]:
df['review'] = df['review'].str.lower()

In [11]:
df

                                                 review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. <br /><br />the...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[10000 rows x 2 columns]

### remove _ html _tags

In [13]:
import re
 
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [15]:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [16]:
remove_html_tags(text)

' Movie 1 Actor - Aamir Khan Click here to download'

In [17]:
# Apply all columns remove html tags

df['review'] = df['review'].apply(remove_html_tags)

In [19]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

### remove _url

In [29]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [27]:
text1 = 'Check out my youtube https://www.youtube.com/dswithbappy'
text2 = 'Check out my linkedin https://www.linkedin.com/in/boktiarahmed73/'
text3 = 'Google search here www.google.com'
text4 = 'For data click https://www.kaggle.com/'

In [31]:
remove_url(text1)

'Check out my youtube '

In [32]:

print(remove_url(text2))
print(remove_url(text3))
print(remove_url(text4))

Check out my linkedin
Google search here
For data click

## Punctuation handling

In [33]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [34]:
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [51]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [48]:
text = 'string. with. punctuation ?'

In [52]:
start= time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1 * 50000)

string with punctuation
14.090538024902344

In [54]:
# 2nd way to punchation remove punctuation 

def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [59]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2 * 5000)

0.2205371856689453

In [60]:
time1/ time2

6.389189189189189

In [61]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [62]:
remove_punc1(df['review'][5])

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

## Char_conversion handle

In [71]:
chat_words = {
    'AFAIK' : 'AS Far As I know',
    'AFK'   : 'Away from keyboard',
    'ASAP'  : 'AS soon as possible'
}

In [72]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)

    return " ".join(new_text)

In [73]:
chat_conversion('Do this work ASAP')

'Do this work AS soon as possible'