In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('covid_toy.csv')

In [ ]:
df.head()

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever'].isnull().sum()
#there are missing value (10)

np.int64(10)

In [ ]:
df['age'].isnull().sum()
# (0) there are not missing value

np.int64(0)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x = df.drop(columns = ['has_covid'])
y = df['has_covid']

In [ ]:
y

In [ ]:
x

In [10]:
X_train, X_test, Y_train,Y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [11]:
X_train.shape

(80, 5)

In [12]:
X_test.shape

(20, 5)

In [13]:
Y_train.shape

(80,)

In [14]:
Y_test.shape

(20,)

In [ ]:
# without - column Tranformation

In [16]:
from sklearn .impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [18]:
si = SimpleImputer()

In [ ]:
df.head()

In [24]:
# adding simple imputer to fever column
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [ ]:
X_train_fever

In [32]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories = [['Mild', 'Strong']])# apply the mild and strong 
X_train_cough = oe.fit_transform(X_train[['cough']])

# Also the test data 
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [ ]:
X_train_cough

In [30]:
# OneHotEncoding - > gender, city

ohe = OneHotEncoder(drop='first',sparse_output=False)

X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [ ]:
X_train_gender_city

In [58]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [41]:
# Extracting Age 
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# Also the test dat 
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [ ]:
X_train_age

In [46]:
# Concatenate 
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city),axis=1) # axis=1 column wise

X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city),axis=1)

X_train_transformed.shape

(80, 6)

In [ ]:
X_train_transformed

In [50]:
# with column Transformer

from sklearn.compose import ColumnTransformer

In [ ]:
transformer = ColumnTransformer( transformers= [
    ('tnf1', SimpleImputer(),['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False, drop='first'),['gender','city'])
],remainder='passthrough')

# has_covid colum we don't remove or edit

In [52]:
transformer.fit_transform(X_train).shape

(80, 7)

In [54]:
transformer.fit_transform(X_test).shape

(20, 7)

In [55]:
new_data = transformer.fit_transform(X_train)

In [ ]:
new_data

In [57]:
# convert data frame :
pd.DataFrame(new_data)

        0    1    2    3    4    5     6
0   101.0  0.0  0.0  0.0  0.0  1.0  81.0
1   100.0  0.0  0.0  0.0  1.0  0.0   5.0
2   100.0  0.0  0.0  0.0  1.0  0.0  19.0
3   100.0  0.0  1.0  1.0  0.0  0.0  27.0
4   103.0  0.0  0.0  1.0  0.0  0.0  73.0
..    ...  ...  ...  ...  ...  ...   ...
75  102.0  1.0  0.0  0.0  0.0  0.0  24.0
76  104.0  1.0  0.0  1.0  0.0  0.0  75.0
77  104.0  0.0  1.0  0.0  0.0  0.0  51.0
78  102.0  1.0  0.0  0.0  1.0  0.0  82.0
79  100.0  1.0  0.0  0.0  1.0  0.0  11.0

[80 rows x 7 columns]